spring:
  redis :
    host: 10.10.10.146
    port : 6379       # Redis服务器连接端口
    password :        # Redis服务器连接密码（默认为空）
    pool:
      max-active : -1  # 连接池最大连接数（使用负值表示没有限制）
      max-idle : 8    # 连接池中的最大空闲连接
      max-wait : -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle : 0    # 连接池中的最小空闲连接
  #============== kafka ===================
  kafka:
#    bootstrap-servers: 10.10.10.143:9092,10.10.10.144:9092,10.10.10.145:9092
#    bootstrap-servers: 127.0.0.1:9092
    bootstrap-servers: 10.10.10.146:9092
    consumer:
      group.id: quoteGroup
      client.id: quoteGroup
      enable.auto.commit: true
      auto.commit.interval.ms: 1000
      session.timeout.ms: 30000
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topics: match_trade_ETHBTC
 #日志配置
logging:
  level:
    root: info




