spring:
  influx:
    dbname: rifles
    url: http://10.10.10.146:8086
  datasource:
    url: jdbc:mysql://10.10.10.230:3306/rifles?characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: viewfin
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20
  auth-redis :
    host: 10.10.10.230
    port : 6379       # Redis服务器连接端口
    password :        # Redis服务器连接密码（默认为空）
    pool:
      max-active : -1  # 连接池最大连接数（使用负值表示没有限制）
      max-idle : 8    # 连接池中的最大空闲连接
      max-wait : -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle : 0    # 连接池中的最小空闲连接
  redis :
    host: 10.10.10.146
    port : 6379       # Redis服务器连接端口
    password :        # Redis服务器连接密码（默认为空）
    pool:
      max-active : -1  # 连接池最大连接数（使用负值表示没有限制）
      max-idle : 8    # 连接池中的最大空闲连接
      max-wait : -1   # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle : 0    # 连接池中的最小空闲连接
  #============== kafka ===================
  kafka:
#    bootstrap-servers: 10.10.10.143:9092,10.10.10.144:9092,10.10.10.145:9092
#    bootstrap-servers: 127.0.0.1:9092
    bootstrap-servers: 10.10.10.146:9092
    consumer:
      group.id: quoteGroup
      client.id: quoteGroup
      enable.auto.commit: true
      auto.commit.interval.ms: 1000
      session.timeout.ms: 30000
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topics: match_trade_ETCUSD
            match_trade_TRXUSD
            match_trade_EOSUSD
            match_trade_LTCUSD
            match_trade_BCHUSD
            match_trade_BTCUSD
            match_trade_ETHUSD
            match_trade_ETCBTC
            match_trade_TRXBTC
            match_trade_EOSBTC
            match_trade_LTCBTC
            match_trade_BCHBTC
            match_trade_ETHBTC
            match_trade_ETCETH
            match_trade_TRXETH
            match_trade_EOSETH
            match_trade_LTCETH
            match_trade_BCHETH

  data:
    mongodb:
      uri: mongodb://viewfin:dev@10.10.10.146:27017/rifles


mybatis:
 mapper-locations: classpath:mapper/*.xml
 type-aliases-package:

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check

#influxdb配置
rifles:
  influxdb:
    dbname: rifles
    url: http://10.10.10.146:8086
    username:
    password:

 #日志配置
logging:
  level:
    root: info




